// <auto-generated />
using System;
using Ace_cars.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ace_cars.Migrations
{
    [DbContext(typeof(AceAutoDealersContext))]
    [Migration("20201116212923_update-tables")]
    partial class updatetables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ace_cars.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CarId");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Ace_cars.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("CarId");

                    b.Property<int?>("HeardAboutUs");

                    b.Property<int?>("HeardAboutUsNavigationId");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("VisitDate");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("HeardAboutUsNavigationId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Ace_cars.Models.HeardAboutUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("HeardAboutUs");
                });

            modelBuilder.Entity("Ace_cars.Models.Customer", b =>
                {
                    b.HasOne("Ace_cars.Models.Car", "Car")
                        .WithMany("Customer")
                        .HasForeignKey("CarId");

                    b.HasOne("Ace_cars.Models.HeardAboutUs", "HeardAboutUsNavigation")
                        .WithMany("Customer")
                        .HasForeignKey("HeardAboutUsNavigationId");
                });
#pragma warning restore 612, 618
        }
    }
}
